#!/usr/bin/env bash
# Idempotently generate the local secrets the compose stack needs, so a fresh
# clone can run `make test-e2e` with nothing checked in but source. Everything
# it writes (certs, keys, .env) is gitignored -- never committed.
#
# Safe to re-run: each artifact is only generated if absent.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

PRINTER_PASS="e2e-printer-passphrase"

# 1. mTLS PKI (cloud <-> printer). gen.sh writes ca/cloud/printer cert+key.
if [ ! -f infra/certs/ca-cert.pem ]; then
  echo "==> Generating mTLS PKI"
  bash infra/certs/gen.sh
fi

# 2. JWT RS256 signing keypair.
if [ ! -f infra/certs/jwt-private.pem ]; then
  echo "==> Generating JWT keypair"
  bash infra/certs/gen-jwt-keys.sh
fi

# 3. Printer document keypair (RSA-4096, private half encrypted at rest). The
#    public half becomes the seeded mailbox's public_key_pem.
if [ ! -f infra/certs/printer-private.pem ]; then
  echo "==> Generating printer document keypair"
  PRINTER_KEY_PASSPHRASE="$PRINTER_PASS" bash infra/certs/gen-printer-keys.sh
fi

# 4. .env with real (non-production) values.
if [ ! -f .env ]; then
  echo "==> Writing .env"
  KMS="$(openssl rand -base64 32)"
  cat > .env <<EOF
# Generated by scripts/e2e/bootstrap.sh for local E2E. Gitignored, non-production.
POSTGRES_USER=automail
POSTGRES_PASSWORD=changeme
POSTGRES_DB=automail
REDIS_PASSWORD=changeme
MINIO_ROOT_USER=automail
MINIO_ROOT_PASSWORD=changeme123
MINIO_KMS_SECRET_KEY=automail-sse-key:${KMS}
DEV_MODE=true
JWT_PRIVATE_KEY_PATH=infra/certs/jwt-private.pem
JWT_PUBLIC_KEY_PATH=infra/certs/jwt-public.pem
APP_ENCRYPTION_KEY=e2e-app-encryption-key-do-not-use-in-prod
PRINTER_PRIVATE_KEY_PATH=infra/certs/printer-private.pem
PRINTER_KEY_PASSPHRASE=${PRINTER_PASS}
MTLS_CA_CERT_PATH=infra/certs/ca-cert.pem
MTLS_CLOUD_CERT_PATH=infra/certs/cloud-server-cert.pem
MTLS_CLOUD_KEY_PATH=infra/certs/cloud-server-key.pem
MTLS_PRINTER_CERT_PATH=infra/certs/printer-cert.pem
MTLS_PRINTER_KEY_PATH=infra/certs/printer-key.pem
EOF
fi

echo "==> Bootstrap complete."
