// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuditEvent struct {
	ID        uuid.UUID     `json:"id"`
	JobID     uuid.UUID     `json:"job_id"`
	Action    string        `json:"action"`
	ActorID   uuid.NullUUID `json:"actor_id"`
	Timestamp time.Time     `json:"timestamp"`
}

type Building struct {
	ID        uuid.UUID `json:"id"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
}

type Job struct {
	ID             uuid.UUID      `json:"id"`
	SenderID       uuid.NullUUID  `json:"sender_id"`
	GuestTokenHash sql.NullString `json:"guest_token_hash"`
	MailboxID      uuid.UUID      `json:"mailbox_id"`
	SlotID         uuid.UUID      `json:"slot_id"`
	EncryptedKey   []byte         `json:"encrypted_key"`
	BlobRef        string         `json:"blob_ref"`
	PageCount      int32          `json:"page_count"`
	Status         string         `json:"status"`
	RetryCount     int32          `json:"retry_count"`
	BlobExpiresAt  sql.NullTime   `json:"blob_expires_at"`
	BlobDeletedAt  sql.NullTime   `json:"blob_deleted_at"`
	CreatedAt      time.Time      `json:"created_at"`
	DeliveredAt    sql.NullTime   `json:"delivered_at"`
}

type Mailbox struct {
	ID              uuid.UUID    `json:"id"`
	BuildingID      uuid.UUID    `json:"building_id"`
	PublicKeyPem    string       `json:"public_key_pem"`
	Status          string       `json:"status"`
	LastHeartbeatAt sql.NullTime `json:"last_heartbeat_at"`
	CreatedAt       time.Time    `json:"created_at"`
}

type MailboxSlot struct {
	ID         uuid.UUID `json:"id"`
	MailboxID  uuid.UUID `json:"mailbox_id"`
	SlotNumber int32     `json:"slot_number"`
	MaxCount   int32     `json:"max_count"`
	CreatedAt  time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	SenderID  uuid.UUID    `json:"sender_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Resident struct {
	ID        uuid.UUID `json:"id"`
	SlotID    uuid.UUID `json:"slot_id"`
	NameEnc   []byte    `json:"name_enc"`
	CreatedAt time.Time `json:"created_at"`
}

type Sender struct {
	ID           uuid.UUID `json:"id"`
	EmailEnc     []byte    `json:"email_enc"`
	NameEnc      []byte    `json:"name_enc"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}
