// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getActiveRefreshToken = `-- name: GetActiveRefreshToken :one
SELECT id, sender_id, expires_at
FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

type GetActiveRefreshTokenRow struct {
	ID        uuid.UUID `json:"id"`
	SenderID  uuid.UUID `json:"sender_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetActiveRefreshToken(ctx context.Context, tokenHash string) (GetActiveRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveRefreshToken, tokenHash)
	var i GetActiveRefreshTokenRow
	err := row.Scan(&i.ID, &i.SenderID, &i.ExpiresAt)
	return i, err
}

const getSenderByEmail = `-- name: GetSenderByEmail :one
SELECT id, email_enc, password_hash, role
FROM senders
WHERE pgp_sym_decrypt(email_enc, $1) = $2::text
`

type GetSenderByEmailParams struct {
	AppKey string `json:"app_key"`
	Email  string `json:"email"`
}

type GetSenderByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	EmailEnc     []byte    `json:"email_enc"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
}

// Same decrypt-then-compare approach as SearchRecipients -- email_enc has
// no plaintext index, so this is a full scan at prototype scale.
func (q *Queries) GetSenderByEmail(ctx context.Context, arg GetSenderByEmailParams) (GetSenderByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getSenderByEmail, arg.AppKey, arg.Email)
	var i GetSenderByEmailRow
	err := row.Scan(
		&i.ID,
		&i.EmailEnc,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const getSenderByID = `-- name: GetSenderByID :one
SELECT id, password_hash, role
FROM senders
WHERE id = $1
`

type GetSenderByIDRow struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
}

func (q *Queries) GetSenderByID(ctx context.Context, id uuid.UUID) (GetSenderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSenderByID, id)
	var i GetSenderByIDRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.Role)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (job_id, action, actor_id) VALUES ($1, $2, $3)
`

type InsertAuditEventParams struct {
	JobID   uuid.UUID     `json:"job_id"`
	Action  string        `json:"action"`
	ActorID uuid.NullUUID `json:"actor_id"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent, arg.JobID, arg.Action, arg.ActorID)
	return err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (
  sender_id, guest_token_hash, mailbox_id, slot_id,
  encrypted_key, blob_ref, page_count
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, status
`

type InsertJobParams struct {
	SenderID       uuid.NullUUID  `json:"sender_id"`
	GuestTokenHash sql.NullString `json:"guest_token_hash"`
	MailboxID      uuid.UUID      `json:"mailbox_id"`
	SlotID         uuid.UUID      `json:"slot_id"`
	EncryptedKey   []byte         `json:"encrypted_key"`
	BlobRef        string         `json:"blob_ref"`
	PageCount      int32          `json:"page_count"`
}

type InsertJobRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// Every job starts 'submitted' (the schema default). Phase 4's
// tryDispatch runs immediately after insert and moves it to
// 'dispatching' (immediate dispatch) or 'queued' (blocked, added to the
// jobs:pending Redis Stream) -- see CreateJob in handlers/jobs.go.
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (InsertJobRow, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.SenderID,
		arg.GuestTokenHash,
		arg.MailboxID,
		arg.SlotID,
		arg.EncryptedKey,
		arg.BlobRef,
		arg.PageCount,
	)
	var i InsertJobRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (sender_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type InsertRefreshTokenParams struct {
	SenderID  uuid.UUID `json:"sender_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken, arg.SenderID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const lockJobForDispatch = `-- name: LockJobForDispatch :one
SELECT id, mailbox_id, slot_id, encrypted_key, blob_ref, status
FROM jobs
WHERE id = $1 AND status IN ('submitted', 'queued')
FOR UPDATE NOWAIT
`

type LockJobForDispatchRow struct {
	ID           uuid.UUID `json:"id"`
	MailboxID    uuid.UUID `json:"mailbox_id"`
	SlotID       uuid.UUID `json:"slot_id"`
	EncryptedKey []byte    `json:"encrypted_key"`
	BlobRef      string    `json:"blob_ref"`
	Status       string    `json:"status"`
}

// Phase 4 double-dispatch guard (plans/03-scaling.md "Dispatch Eligibility
// Check"). Must run inside a transaction alongside MarkJobDispatching --
// NOWAIT means a second node racing for the same row gets an immediate
// 55P03 lock_not_available error instead of blocking, so it can fall
// through to "someone else has this" and move on to the next job rather
// than stall a connection. Only 'submitted' or 'queued' rows are
// claimable: 'dispatching'/'printing'/'delivered'/'failed' are already
// spoken for or terminal.
func (q *Queries) LockJobForDispatch(ctx context.Context, id uuid.UUID) (LockJobForDispatchRow, error) {
	row := q.db.QueryRowContext(ctx, lockJobForDispatch, id)
	var i LockJobForDispatchRow
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.SlotID,
		&i.EncryptedKey,
		&i.BlobRef,
		&i.Status,
	)
	return i, err
}

const markJobDispatching = `-- name: MarkJobDispatching :exec
UPDATE jobs SET status = 'dispatching' WHERE id = $1
`

// Second half of the claim transaction started by LockJobForDispatch.
func (q *Queries) MarkJobDispatching(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markJobDispatching, id)
	return err
}

const requeueJob = `-- name: RequeueJob :exec
UPDATE jobs SET status = 'queued' WHERE id = $1
`

// Reverts a claimed job back to 'queued' when the publish to
// mailbox:<id>:dispatch finds zero subscribers (printer link not held by
// any live node -- plans/05-cloud-server.md "Presence and liveness").
func (q *Queries) RequeueJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, requeueJob, id)
	return err
}

const resolveRecipient = `-- name: ResolveRecipient :one
SELECT
  residents.id AS recipient_id,
  mailbox_slots.id AS slot_id,
  mailboxes.id AS mailbox_id,
  mailboxes.public_key_pem
FROM residents
JOIN mailbox_slots ON mailbox_slots.id = residents.slot_id
JOIN mailboxes ON mailboxes.id = mailbox_slots.mailbox_id
WHERE residents.id = $1
`

type ResolveRecipientRow struct {
	RecipientID  uuid.UUID `json:"recipient_id"`
	SlotID       uuid.UUID `json:"slot_id"`
	MailboxID    uuid.UUID `json:"mailbox_id"`
	PublicKeyPem string    `json:"public_key_pem"`
}

// Resolves a recipient_id (residents.id) to everything POST /jobs needs:
// the mailbox's public key (for the sender to wrap their AES key) and the
// slot_id/mailbox_id the sender never sees directly.
func (q *Queries) ResolveRecipient(ctx context.Context, id uuid.UUID) (ResolveRecipientRow, error) {
	row := q.db.QueryRowContext(ctx, resolveRecipient, id)
	var i ResolveRecipientRow
	err := row.Scan(
		&i.RecipientID,
		&i.SlotID,
		&i.MailboxID,
		&i.PublicKeyPem,
	)
	return i, err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const searchRecipients = `-- name: SearchRecipients :many

SELECT
  residents.id AS recipient_id,
  pgp_sym_decrypt(residents.name_enc, $1) AS full_name,
  buildings.address AS building_address
FROM residents
JOIN mailbox_slots ON mailbox_slots.id = residents.slot_id
JOIN mailboxes ON mailboxes.id = mailbox_slots.mailbox_id
JOIN buildings ON buildings.id = mailboxes.building_id
WHERE pgp_sym_decrypt(residents.name_enc, $1) ILIKE '%' || $2::text || '%'
   OR buildings.address ILIKE '%' || $2::text || '%'
ORDER BY full_name
LIMIT 20
`

type SearchRecipientsParams struct {
	AppKey string `json:"app_key"`
	Query  string `json:"query"`
}

type SearchRecipientsRow struct {
	RecipientID     uuid.UUID `json:"recipient_id"`
	FullName        string    `json:"full_name"`
	BuildingAddress string    `json:"building_address"`
}

// sqlc query definitions. plans/08-data-models.md is the schema source of
// truth; these are the Phase 2 queries (recipients, jobs, audit log).
// `app_key` arguments are pgcrypto's symmetric key for PII columns -- see
// docs/study/07-pgcrypto-pii-encryption.md for why it travels in the SQL
// call instead of staying purely in application code.
// Resident name is pgcrypto-encrypted, so the match has to happen after
// decrypting each row -- there is no index on plaintext name. Fine at
// prototype scale; a real directory would need a separate searchable
// index (e.g. a deterministic blind-index column) to avoid scanning
// every resident row per search.
func (q *Queries) SearchRecipients(ctx context.Context, arg SearchRecipientsParams) ([]SearchRecipientsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchRecipients, arg.AppKey, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRecipientsRow
	for rows.Next() {
		var i SearchRecipientsRow
		if err := rows.Scan(&i.RecipientID, &i.FullName, &i.BuildingAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $1,
    delivered_at = CASE WHEN $1 = 'delivered' THEN now() ELSE delivered_at END
WHERE id = $2
RETURNING id, mailbox_id, blob_ref, status
`

type UpdateJobStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

type UpdateJobStatusRow struct {
	ID        uuid.UUID `json:"id"`
	MailboxID uuid.UUID `json:"mailbox_id"`
	BlobRef   string    `json:"blob_ref"`
	Status    string    `json:"status"`
}

// Applied from "status" printer-link frames (plans/05-cloud-server.md
// "Status frames"). Phase 3 only ever writes 'delivered' (the dev-mode
// stub dispatch always succeeds); 'printing' and 'failed' transitions
// are exercised for real once Phase 4 implements actual dispatch retries.
// delivered_at is set only on the 'delivered' transition.
func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (UpdateJobStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateJobStatus, arg.Status, arg.ID)
	var i UpdateJobStatusRow
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.BlobRef,
		&i.Status,
	)
	return i, err
}
